### ISSUE TITLE
May I ask why htseq-clip used first/second mate for pair-end crosslink sites extraction ? 

### ISSUE THREAD

**Issue by TingheZhang** [EMBL-Hentze-group/htseq-clip#9]
Hi, 

I am new to iCLIP/eCLIP analysis. 

I have read the paper and document for htseq-clip and it will be very helpful for CLIP data anaylsis.

But I do not understand why htseq-clip used first/second mate for pair-end crosslink sites extraction. 
May I ask for the reason ? 

What will be disadvantage if it used both pair for pair-end ? 

Thanks

**Comment by Distue** [comment]
Hi Ting-He Zhang,

iCLIP/eCLIP seq are single-nucleotide resolution sequencing methods which
infer the position of the nucleotide position by truncation. That means
that the position where you assume the single-nucleotide crosslink happened
is 1 nucleotide adjacent from the end of the insert (the bit you sequence).

The insert is sequenced either single-read or paired-end. If you sequence
paired-end, you need to specify where you want the one-nucleotide position
extracted from, mate 1 or mate 2. This can vary depending on the protocol
and library generation.

Technically, htseq-clip is using all paired-end information but extracts
the precise single-nucleotide position.

Currently, the newer protocols opt for single-read setups, because the
insert sizes are in general very short and other technical reasons.

Hope this helps,
Tom

Ting-He Zhang ***@***.***> schrieb am Fr., 17. Feb. 2023,
21:31:
